### ISSUE TITLE
Use of optional types

### ISSUE THREAD

**Issue by stevensona** [wildswine/noahsark#5]
I wanted to go through and refactor Board to make use of Optional types. The purpose being eliminate a lot of the null checking involved with several methods necessary because of the decision to represent an empty spot in the board as 'null'. Optional seemed to be the answer to this. However, upon further research into the idiomatic use of Optional types, I have decided against it for the time being.

**Comment by caryanne** [comment]
As long as it is known that 'null' in the case of the ArrayList of pieces is *used* to designate a blank space on the board, it is ok from a design standpoint.
